import * as yup from "yup";
// import phoneRegExp from "@utils/phoneRegExp";

const schema = yup.object().shape({
  //   nomeFantasia: yup
  //     .string()
  //     .required("Preencha seu o nome Fantasia da empresa"),
  //   email: yup.string().required("Preencha o email").email("Email invalido"),
  //   telefone1: yup.string().matches(phoneRegExp, "Telefone invalido"),
  //   telefone2: yup.string().matches(phoneRegExp, "Telefone invalido"),
  //------------------------------------------------
  //   pathLogotipoLoja: "",
  //   EstadualLoja: "",
  cnpjLoja: yup.string().required("CNPJ obrigatorio"),
  isEstadualLoja: yup.string().required("Inscricao Estadual obrigatoria"),
  isMunicipalLoja: yup.string().required("Inscricao Municipal obrigatoria"),
  nomeLoja: yup.string().required("Nome obrigatorio"),
  enderecoLoja: yup.string().required("Endereco obrigatorio"),
  numeroEnderecoLoja: yup.string().required("Numero obrigatorio"),
  //complementoEnderecoLoja: yup.string().required("Complemento obrigatorio"),
  complementoNumeroEnderecoLoja: yup
    .string()
    .required("Complemento obrigatorio"),
  bairroEnderecoLoja: yup.string().required("Bairro obrigatorio"),
  cidadeEnderecoLoja: yup.string().required("Cidade obrigatorio"),
  estadoEnderecoLoja: yup.string().required("Estado obrigatorio"),
  cepEnderecoLoja: yup.string().required("CEP obrigatorio"),
  dddTelefone1Loja: yup.string().required("DDD obrigatorio"),
  Telefone1Loja: yup.string().required("Telefone obrigatorio"),

  //   emailLoja: "",
  //   dddTelefone1Loja: "",
  //   idUltEnvelopeLoja: "",
  //   FaxLoja: "",
  //   dddFaxLoja: "",
  // siteLoja: yup.string().url("Url invalido"),
  //   estadoEnderecoLoja: "",
  //   bairroEnderecoLoja: "",
  //   Telefone2Loja: "",
  //   dddTelefone3Loja: "",
  //   cepEnderecoLoja: "",
  //   Telefone3Loja: "",
  //   statusPagamentoLoja: "",
  //   dtIniAssinaturaLoja: "",
  //   nomeArqLogoLoja: "",
  //   habilitaIcarrosLoja: "",
  //   senhaIcarrosLoja: "",
  //   loginIcarrosLoja: "",
  //   vagasICarrosLoja: "",
  //   habilitaWebMotorsLoja: "",
  //   senhaWebMotorsLoja: "",
  //   loginWebMotorsLoja: "",
  //   vagasWebMotorsLoja: "",
  //   habilitaZapLoja: "",
  //   senhaZapLoja: "",
  //   loginZapLoja: "",
  //   vagasZapLoja: "",
  //   habilitaOpcionaisPreco: "",
  //   habilitaPronto: "",
  //   habilitaVM: "",
  //   habilitaFoto: "",
  //   habilitaVSILoja: "",
  //   habilitaEmissaoReciboLoja: "",
  //   nomeJSPEmissaoReciboLoja: "",
  //   habilitaTermoGarantiaLoja: "",
  //   nomeJSPTermoGarantiaLoja: "",
  //   habilitaTermoResponsabilidadeLoja: "",
  //   nomeJSPTermoResponsabilidadeLoja: "",
  //   habilitaEmissaoReciboVendaLoja: "",
  //   nomeJSPEmissaoReciboVendaLoja: "",
  //   habilitaTermoCienciaGarantiaLoja: "",
  //   nomeJSPTermoCienciaGarantiaLoja: "",
  //   habilitaAvaliacoesLoja: "",
  //   nomeJSPTermoConsignacaoLoja: "",
  //   habilitaTermoConsignacaoLoja: "",
});
export default schema;
